---
- hosts: localhost
  connection: local

  tasks:
    - name: Install packages
      zypper:
        name: "{{ item }}"
        state: latest
      loop:
        - zip
        - curl
        - htop
        - chromium
        - obs-studio

    - name: Setup /etc/hosts
      get_url:
        url:  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
        dest: /etc/hosts

    - name: Install nvm
      shell: curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      args:
        creates: "/home/{{ WORKSTATION_USER }}/.nvm"
      become: yes
      become_user: "{{ WORKSTATION_USER }}"

    - name: Install zoom
      zypper:
        name: https://zoom.us/client/latest/zoom_openSUSE_x86_64.rpm
        state: present
        disable_gpg_check: yes

    - import_tasks: wireshark.yml
    - import_tasks: sdkman.yml
    - import_tasks: docker.yml
    - import_tasks: idea.yml
    - import_tasks: packman-repo.yml

# TODO: code, postman

