---
- hosts: localhost
  connection: local

  tasks:
    - import_tasks: sdkman.yml
    - import_tasks: docker.yml
    - import_tasks: obs.yml
    - import_tasks: wireshark.yml

    - name: Setup /etc/hosts
      get_url:
        url:  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
        dest: /etc/hosts

    - name: Install nvm
      shell: curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      args:
        creates: "/home/{{ WORKSTATION_USER }}/.nvm"
      become: yes
      become_user: "{{ WORKSTATION_USER }}"

    - name: Install snaps
      snap:
        name: "{{ item.name }}"
        classic: "{{ item.classic }}"
      loop:
        - { name: 'intellij-idea-ultimate', classic: true }
        - { name: 'code', classic: true }
        - { name: 'chromium', classic: false }
        - { name: 'postman', classic: false}

    - name: Install packages
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: latest
      loop:
        - htop
        - timeshift
