---
- hosts: localhost
  connection: local

  tasks:
    - import_tasks: various_packages.yml
    - import_tasks: sdkman.yml
    - import_tasks: docker.yml

    - name: Setup /etc/hosts
      get_url:
        url:  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
        dest: /etc/hosts

    - name: Install nvm
      shell: curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      args:
        creates: "/home/melnichuk/.nvm"
      become: yes
      become_user: melnichuk
